### ISSUE TITLE
Using gometalinter in travis yaml

### ISSUE THREAD

**Issue by njuettner** [akamai/AkamaiOPEN-edgegrid-golang#11]
Fixes issues like:

- error return value not checked
- multiple string occurrence(s)
- not exported methods, types and functions
- undeclared name
- unused struct field
- error strings should not be capitalized or end with punctuation or a newline
- ineffectual assignment

...

**Comment by dshafik** [comment]
I installed this today, and wow that's a lot of errors. Looks like it even picks up on bad naming conventions (e.g. `BodyJson` rather than `BodyJSON` and `ApiError` rather than `APIError`) which I'm all for.

I support doing this, but it should not be required for a test pass.

**Comment by robertolopezlopez** [comment]
Closed due to inactivity. On the other hand, this has become outdated: we use golangci-lint + revive nowadays
