### ISSUE TITLE
Add Network list pkg into client

### ISSUE THREAD

**Issue by partamonov** [akamai/AkamaiOPEN-edgegrid-golang#121]
We would like to port network list functionality and code from https://github.com/apiheat/go-edgegrid/tree/master/service/netlistv2 and add it here, as we plan later to use it for terraform resources.

Please let me know if you are fine with that and that we will not be doing same work as you.
@dshafik

**Comment by dshafik** [comment]
@partamonov  I'm no longer with Akamai, perhaps @javiergarza can answer?

**Comment by atuljain16** [comment]
@partamonov Networklist will a sub provider in TF similar to Appsec. We are developing the client code with better logging and better complaint with other API clients in GOLANG Edgegrid. Updated NL client code will be available on Mar 1st.

**Comment by lkowalsk-akamai-com** [comment]
Hi @partamonov , this functionality is now available.

**Comment by partamonov** [comment]
Top.
