### ISSUE TITLE
Updating GTM weights

### ISSUE THREAD

**Issue by iamshreeram** [akamai/AkamaiOPEN-edgegrid-golang#127]
We want to update the GTM weights through "AkamaiOPEN-edgegrid-golang". 

We are currently using below approach
```
req, _ := client.NewJSONRequest(config, "PUT", "/config-gtm/v1/domains/{domainname}/properties/{gtmname}", body)
resp, _ := client.Do(config, req)
```
`config` has the token details,
`body` has the actual payload that we use in making the API (PUT) call

It works with REST client (POSTMAN). But while using the same payload with `client.NewJSONRequest`, we are seeing below error 
```
{
  "type" : "https://problems.luna.akamaiapis.net/config-gtm/v1/illegalBody",
  "title" : "Illegal request body",
  "instance" : "<instance-id>",
  "status" : 422,
  "detail" : "The JSON request body contained a syntax error",
  "problemId" : "<problem-id>"
}
```

**Comment by edglynes** [comment]
@iamshreeram Pls provide the body content. If you want to limit visibility, pls email to elynes@akamai.com

AkamaiOPEN-edgegrid-golang has a configgtm package which should be your preferred entry points. See https://github.com/akamai/AkamaiOPEN-edgegrid-golang/configgtm-v1_4
Specifically the endpoints in https://github.com/akamai/AkamaiOPEN-edgegrid-golang/configgtm-v1_4/property.go

**Comment by iamshreeram** [comment]
@edglynes , thanks for looking into this.

After some research, We are currently using `NewJSONRequest` from `client-v1`. 
```
	req, _ := client.NewJSONRequest(config, "PUT", uri, gtmbody)
	resp, _ := client.Do(config, req)
```
This works. 

Thanks!

**Comment by iamshreeram** [comment]
Just to clarify - Even `configgtm-v1_4/property.go` internally uses the same approach. Thanks!
