### ISSUE TITLE
how can I increase body size limit for http POST request

### ISSUE THREAD

**Issue by mortenko** [akamai/AkamaiOPEN-edgegrid-golang#147]
Hi folks,

I'm implementing this go client into my crossplane provider.

I'm calling createProperty func from PAPI API, which returns me an error:  **401 Unauthorized: The signature does not match**. I need to increase body size limit for http request. Is there any supporting function for that ? 

Thanks

**Comment by mortenko** [comment]
Hi @robertolopezlopez, 
Credentials were okey. This error does not mean 100% that is related to bad credentials. 

I was browsing closed issues here and I found solution. I needed to increase body size limit ...but I didn't know where I can set it up but I found it after while. You can do it by providing value to property MaxBody  in following [config struct](https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/5bf72bbd23d4bfe8fcec060cb2962f7da96a9247/pkg/edgegrid/config.go#L42).

btw using v2 branch

**Comment by robertolopezlopez** [comment]
Hi @mortenko ,

My exact words were `...401 usually means that...` (**usually**). In any case, it is worth to verify that before getting into detail, even more when you had not given any yet.

Yes, modifying `MaxBody` will give you bigger body size. Try passing that Option [when you create your config](https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/5bf72bbd23d4bfe8fcec060cb2962f7da96a9247/pkg/edgegrid/config.go#L62).

In any case and given that you seem to have found a solution to your problem already, I will close this issue. Please reopen it if your problem persists.

Kind regards,

Roberto
