### ISSUE TITLE
add IP to network-lists gives 422 Unprocessable Request

### ISSUE THREAD

**Issue by atefhaloui** [akamai/AkamaiOPEN-edgegrid-golang#151]
Hi,
I'm developing a crowdsec bouncer that will add banned IP adresses to an IP blacklist.
I've developed a tiny library around the network-list API: https://github.com/atefhaloui/akamai-network-lists
Everytime I test adding new IP to my IP blacklist I receive **422** Unprocessable Request
```
{
  "detail": "The entry 195.109.4.59/32 already exists in the list",
  "instance": "https://problems.luna.akamaiapis.net/network-lists-activation/error-instances/6c94c1aa-df40-436e-b04e-1a8935194ca2",
  "status": 422,
  "title": "The instructions in this request cannot be procesed",
  "type": "https://problems.luna.akamaiapis.net/network-lists-activation/error-types/UNPROCESSABLE-REQUEST"
}
```
However, when looking in the Control Center --> Security Configurations --> Network List, the IP has been correctly added and the network list is set as "MODIFIED" and ready to be activated.

Do anyone know why I'm receiving this 422 error ?

Thank you

**Comment by securitylevelup** [comment]
Hi Atef, 

Not 100% sure which API operation you are using to add IP ranges to your network list. Are you using the POST /network-lists/{id}/append operation which appends the IP range to the list?

The error shows the IP is already in there and with the append operation you will want to only add the new IP range, not existing ones. I hope that helps!

**Comment by atefhaloui** [comment]
Hi,
   It seems that I've used the wrong http method when calling the add API.
Now, I'm keeping track of the Link as received from the call to https://techdocs.akamai.com/network-lists/reference/get-network-list and my tests are OK ;)

Thank you for your help.
