### ISSUE TITLE
v2: appsec. UpdateWAFProtection misses request body

### ISSUE THREAD

**Issue by jbrmg** [akamai/AkamaiOPEN-edgegrid-golang#153]
The appsec.UpdateWAFProtection request misses the request body. To disable/enable the WAF protection, the following request body must be submitted:

```json
{"protections":{"APP_LAYER_RULES":false|true}}
```

https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/c3d0642716ac158fb5fb950c16d9b0d6ae00b205/pkg/appsec/waf_protection.go#L195

Using the method right now leads to an internal server error as the body is missing:

```json
{
    "type": "https://problems.luna.akamaiapis.net/appsec/error-types/INTERNAL-SERVER-ERROR",
    "status": 500,
    "title": "Internal Server Error",
    "detail": "Error occurred while processing the request.",
    "instance": "https://problems.luna.akamaiapis.net/appsec/error-instances/<id>"
}
```

**Comment by kaush-** [comment]
Hi @jbrmg,

Thank you for bringing this issue to our notice. We will get back to you as soon as we have an update of this.

Regards,
Piyush

**Comment by kaush-** [comment]
Hi @jbrmg,

Our team can see the message body being passed correctly ('{"applyApplicationLayerControls":false}'). Could it be that you are mistaking the nil passed as the last parameter in the quoted line of code, but that's not the message body. (The message body is the 'params' argument a few lines after that\.) Can you please confirm if you are still seeing this issue, and if so please supply the resulting terraform.log file?

Regards,
Piyush

**Comment by jbrmg** [comment]
Hi @kaush- ,

thanks for the response. I can confirm that I am still seeing this issue. 

```
2022-05-30T06:36:57.873Z [DEBUG] provider.terraform-provider-akamai_v2.0.0: 2022/05/30 06:36:57 [ERROR] calling UpdateWAFProtection: Title: Internal Server Error; Type: https://problems.luna.akamaiapis.net/appsec-configuration/error-types/INTERNAL-SERVER-ERROR; Detail: Error occurred while processing the request.: APPSEC=resourceWAFProtectionCreate OperationID=906d7195-eeaa-4d62-95e1-9a8e3f2f7214
2022-05-30T06:36:57.877Z [ERROR] vertex "module.policy_block.akamai_appsec_waf_protection.this" error: Title: Internal Server Error; Type: https://problems.luna.akamaiapis.net/appsec-configuration/error-types/INTERNAL-SERVER-ERROR; Detail: Error occurred while processing the request.
```

Although I could figure out that the issue appears only if Terraform attempts to perform the operation immediately after creating the security policy. When executing `terraform apply` for the second time **with some delay (~ 1 minute)**, the issue disappears. Running `terraform apply` again immediately after the failure does not solve the issue.

Should I create an issue in https://github.com/akamai/terraform-provider-akamai instead?

**Comment by kaush-** [comment]
Hi @jbrmg,

Thank you for your response. Yes please raise an issue in TFP-Akamai repo for this, as it will help us with tracking it correctly. We can take it from there.

Let me know if you need any further information.

Regards,
Piyush

**Comment by jbrmg** [comment]
For reference: A issue in the TFP repository has been created: https://github.com/akamai/terraform-provider-akamai/issues/312.
