### ISSUE TITLE
DXE-2723 Network Lists: missing error handling in CreateActivations()

### ISSUE THREAD

**Issue by atefhaloui** [akamai/AkamaiOPEN-edgegrid-golang#187]
Hi,
    I'm playing with the networklists API and it seems that when a 4xx happens when activating a network list the error is not handled. Instead, in the function `CreateActivations()` just after the call to `p.Exec(req, &rval, params)` we're not making a check to `resp.StatusCode` but we're trying to get the new activation status directly --> this call will succeed and the entire call to `CreateActivations()` will succeed.

I think that we must add the following check on line 353 (based on v6.0.0):

```go
	if resp.StatusCode != http.StatusOK {
		return nil, p.Error(resp)
	}
```

Cheers

**Comment by dawiddzhafarov** [comment]
Hi @atefhaloui,

Thank You for opening the issue. At first glance it seem that You are right and those 3 lines of code are missing. We will investigate it further and fix it.

With regards,
Dawid

**Comment by dawiddzhafarov** [comment]
Hi,

Thank You for the feedback. Could You please provide sample configuration You have used (without any sensitive information)? When MaxBody is not provided, it should default to MaxBodySize automatically. Please also provide information about the environment: operating system, edgegrid version.

With regards,
Dawid

**Comment by atefhaloui** [comment]
Hi Dawid,
   As I said, this is a simple documentation issue ;)
In my case, my environment is:
* Linux debian 10 (amd64)
* Golang v1.20
* Edgegrid: v6.0.0
I'm using a global configuration yaml file where I store edgegrid credential so I'm not using  `~/.edgerc`:
```go
	// AkamaiConfig required configuration parameters to initialize the akamai server part.
	EdgeGridConfig struct {
		Host         string   `yaml:"host" validate:"required"`
		ClientToken  string   `yaml:"client_token" validate:"required"`
		ClientSecret string   `yaml:"client_secret" validate:"required"`
		AccessToken  string   `yaml:"access_token" validate:"required"`
		AccountKey   string   `yaml:"account_key,omitempty"`
		HeaderToSign []string `yaml:"headers_to_sign,omitempty"`
		MaxBody      int      `yaml:"max_body,omitempty"`
		RequestLimit int      `yaml:"request_limit,omitempty"`
		Debug        bool     `yaml:"debug,omitempty"`
	}
```
and I'm using a simple copy constructor method
```go
func EdgeGridCredentials(cfg *EdgeGridConfig) *edgegrid.Config {
	conf := edgegrid.Config{
		Host:         cfg.Host,
		ClientToken:  cfg.ClientToken,
		ClientSecret: cfg.ClientSecret,
		AccessToken:  cfg.AccessToken,
		AccountKey:   cfg.AccountKey,
		HeaderToSign: cfg.HeaderToSign,
		MaxBody:      cfg.MaxBody,
		RequestLimit: cfg.RequestLimit,
		Debug:        cfg.Debug,
	}

	// --> without this check will keep getting 401 status with 'signature mismatch' message
	if conf.MaxBody <= 0 {
		conf.MaxBody = edgegrid.MaxBodySize
	}

	return &conf
}
```

Sincerely,
Atef

**Comment by lkowalsk-akamai-com** [comment]
This issue is now fixed with recent release
