### ISSUE TITLE
DXE-3147 ID attribute is missing in Enrollment struct of CPS package 

### ISSUE THREAD

**Issue by adrianeib** [akamai/AkamaiOPEN-edgegrid-golang#195]
Hello all,

I noticed that enrollment ID isn't parsed from the API response.
However ID is needed in other API calls for example [get-deployment-production](https://techdocs.akamai.com/cps/reference/get-deployments-production).

There is a method [ListEnrollments](https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/master/pkg/cps/enrollments.go#L20). It returns [ListEnrollmentsResponse](https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/master/pkg/cps/enrollments.go#L44).  ListEnrollmentsResponse contains list of [Enrollments](https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/master/pkg/cps/enrollments.go#L49). However `ID` isn't parsed but it is returned from API call [get-enrollments](https://techdocs.akamai.com/cps/reference/get-enrollments).

**Comment by Slonimskaia** [comment]
Hi @adrianeib,

Thank you for reporting this issue. We are going to address that. For now, you can parse Enrollment.Location field to get enrollment ID. 

Best regards,
Tatiana Slonimskaia

**Comment by lkowalsk-akamai-com** [comment]
Hi @adrianeib  this should be available already.
