### ISSUE TITLE
Geolocation of Datacenter

### ISSUE THREAD

**Issue by udita-chakraborty** [akamai/AkamaiOPEN-edgegrid-golang#210]
Hello Team ,
Was trying to add datacenter in load-balancer version via -[loadbalancer.go](https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/master/pkg/cloudlets/loadbalancer_version.go#L51). Now city , country , continent are need to be passed , if i dont pass the values of latitude and longitude , call api to activate the version , i get a 400 bad request, because all of this are required fields. However in the akamai portal(ui) , by filling the values of city , country and continent , the values of latitude and longitude auto fills which isn't same via api . Is there any way around ?? Also is there any way akamai could provide geolocation api , so that need not rely on third part api's or services . I have also seen that if i pass wrong values of geolocation , it doesn't complain either , but if i want to have the balancing type as performant , then values should be proper . At the moment , its a becoming a big challenge for my automation which i am doing.

**Comment by PawelSnoch** [comment]
Hello @udita-chakraborty ,
it is not possible to add datacenter without required fields:

- Latitude: is required
- Longitude: is required

It is also not allowed via API _"errorMessage": "object has missing required properties ([\"latitude\",\"longitude\"])"_.

We base on API and that is why these fields are mandatory. But let me ask direct API team about possibility of auto fill latitude and longitude as it is in UI.

BR,
Pawel

**Comment by udita-chakraborty** [comment]
Hey @PawelSnoch , thanks for having a look . 
Yeah Latitude , Longitude , city , country code , continent code  all of these are required fields and thats what i was refering too. It just makes life easier if Akamai provides some geolocation api to the customers or the internal ones which akamai uses to get the co-ordinates based on the values of city , country in the UI . As I am building an api , which will adds the ALB rule , datacenters as conditional-origins  to the property configuration , creates a load-id and add paths in the cloudlet policy , so providing appropiate co-ordinates become crucial for the load-manager setup for a balancing type as performance.

**Comment by PawelSnoch** [comment]
Hi @udita-chakraborty ,
unfortunately there are no plans to provide such function. We recommend one of these geocoder APIs that can be used to translate city/country into latitude/longitude:
	•	Google Places API
	•	GeoNames API
	•	OpenCage Geocoding API
	•	Here Places API
	•	Mapbox Geocoding API
	•	TomTom Search API
Hope it will help you.

BR,
Pawel
