### ISSUE TITLE
Error when getting and updating rules for property

### ISSUE THREAD

**Issue by cgunning** [akamai/AkamaiOPEN-edgegrid-golang#32]
I get the following error when trying to get and update rules for a property
```
API Error: 400 400 Bad Request There was a problem extracting the contract and group id.  Please explicitly pass in the contract id and group id you wish to use. More Info https://problems.luna.akamaiapis.net/papi/v0/problem-extracting-contract-group
```

As a workaround I've implemented my own functions that passes these in the API call. 
```
        # Example for getting rules for property
	req, err := client.NewRequest(
		api.Config,
		"GET",
		fmt.Sprintf(
			"/papi/v1/properties/%s/versions/%d/rules?contractId=%s&groupId=%s",
			prop.PropertyID,
			prop.LatestVersion,
			prop.ContractID,        # These are added
			prop.GroupID,            # These are added
		),
		nil,
	)
```
These lines correspond to https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/master/papi-v1/rules.go#L48-L57

**Comment by cgunning** [comment]
This seems to be a problem with other resources as well. How come that you specify ContractID and GroupID in some API-calls but not others? I'm not very knowledgeable when it comes to the API but it seems lite it should be consistent.

**Comment by cgunning** [comment]
I'd be willing to provide a PR for this if anyone could give me some feedback if there's a reason behind not sending these parameters

**Comment by lkowalsk-akamai-com** [comment]
@cgunning  - Sorry for not looking at this earlier. Please check it with lates version of Edgegrid library. I will be closing this for now, feel free to open new ticket if issue persists.
