### ISSUE TITLE
Missing dependency prevents cli-api-gateway install

### ISSUE THREAD

**Issue by lukaszczerpak** [akamai/AkamaiOPEN-edgegrid-golang#37]
The API Gateway module installation throws the following error:

```
$ akamai install https://github.com/akamai/cli-api-gateway.git
Attempting to fetch command from https://github.com/akamai/cli-api-gateway.git...... [OK]
Installing...... [FAIL]
Unable to build binary: exit status 1
```

After some digging I figured out this is due to a missing dependency `github.com/spf13/cast` in the master CLI package as `apikey-manager-v1` and `api-endpoints-v2` import it but don't specify in the deps file.

**Comment by dshafik** [comment]
@lukaszczerpak this has been resolved with the release of Akamai CLI for API Gateway 0.1.0, can you confirm?

**Comment by lukaszczerpak** [comment]
Yep, works now! Thanks for fixing it.

**Comment by dshafik** [comment]
Thanks for confirming @lukaszczerpak!
