### ISSUE TITLE
how can I insert an HTTP header in client.NewRequest() function?

### ISSUE THREAD

**Issue by peteguan** [akamai/AkamaiOPEN-edgegrid-golang#43]
some RESTful apis in akamai developer need specific http headers such as `PAPI-Use-Prefixes: true`, how can I insert the headers into my post/get requests?

**Comment by dshafik** [comment]
@peteguan to answer your specific question:

```go
req, _ := client.NewRequest(Config, "GET", "/path", nil)
req.Header.Add("PAPI-Use-Prefixes", "true")
```

I am however curious what you're trying to do with PAPI that cannot be done with the `papi` package?

**Comment by peteguan** [comment]
It works, thank you. Some cps apis need a header like `Content-Type: application/vnd.akamai.cps.certificate-history.v1+json`.
Btw, can I use a proxy when I am creating a new request?

**Comment by peteguan** [comment]
@dshafik I would like to use a proxy in my production environment, how can I set my proxy domain for the requests?

**Comment by dshafik** [comment]
@peteguan you should be able to use the standard Golang methods for setting an http proxy, check out https://stackoverflow.com/a/14663620

In particular, I think in your case you may want the second option, where you set it globally:

```go
proxyUrl, err := url.Parse("http://proxyIp:proxyPort")
http.DefaultTransport = &http.Transport{Proxy: http.ProxyURL(proxyUrl)}
```
