### ISSUE TITLE
Invalid gock version?

### ISSUE THREAD

**Issue by qburst-shyam** [akamai/AkamaiOPEN-edgegrid-golang#58]
```shell
$ go get github.com/akamai/AkamaiOPEN-edgegrid-golang
go: finding github.com/h2non/gock v0.0.0-00010101000000-000000000000
go: github.com/h2non/gock@v0.0.0-00010101000000-000000000000: unknown revision 000000000000
go: error loading module requirements
```
I have `go mod` enabled

```shell
$ ls
go.mod
```
`go.mod` file
```
module scratch-space

go 1.12
```

It had worked in the previous version.

https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/v0.9.0/go.mod#L14
> 	gopkg.in/h2non/gock.v1 v1.0.15

Changed to 

https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/v0.9.1/go.mod#L7
> 	github.com/h2non/gock v0.0.0-00010101000000-000000000000
> ...
> replace github.com/h2non/gock => gopkg.in/h2non/gock.v1 v1.0.14

Clues as to what I'm doing wrong?

There isn't an issue when running it without `go mod` afaik.

**Comment by zhubingbing** [comment]
I have encountered the same situation. 
go get: github.com/akamai/AkamaiOPEN-edgegrid-golang@v0.9.0 updating to
	github.com/akamai/AkamaiOPEN-edgegrid-golang@v0.9.1 requires
	github.com/h2non/gock@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

i don't know how to solve it

**Comment by qburst-shyam** [comment]
I was able to solve this, albeit it seems like a temporary fix, by adding
the following line to my *go.mod* file.

*replace github.com/h2non/gock <http://github.com/h2non/gock> =>
gopkg.in/h2non/gock.v1 <http://gopkg.in/h2non/gock.v1> v1.0.14*

If you require the 1.0.15 version, then maybe you can switch to that
version.

Thanks,
Shyam S Kumar
*Q**Burst** | *www.qburst.com
Skype: shyamsalimkumar23

**Comment by martinstibbe** [comment]
Yes this may have come in with mixed gock libraries coming into codebase github.com vs gopkg.in issues in jarvis testing would like to target one standard gock library for entire library stay tuned hope to resolve soon
