### ISSUE TITLE
cps List Enrollments Returns 400 Bad Request

### ISSUE THREAD

**Issue by supernova2468** [akamai/AkamaiOPEN-edgegrid-golang#78]
I'm trying to setup a very simple script to get the list of cps enrollments, but when I run it an error is returned. 

````
package main

import (
	"log"
	"github.com/akamai/AkamaiOPEN-edgegrid-golang/cps-v2"
	"github.com/akamai/AkamaiOPEN-edgegrid-golang/edgegrid"
)

func main() {
	config, _ := edgegrid.Init(".edgerc", "default")
	cps.Init(config)

	contractID := "#-######"
	params := cps.ListEnrollmentsQueryParams{ContractID: contractID}
	enrollments, err := cps.ListEnrollments(params)
	if err != nil {
		log.Panicln(err)
	}
	log.Println(enrollments)
}
````

which returns 
````
2020/04/15 18:48:20 API Error: 400 400 Bad Request  More Info https://problems.luna.akamaiapis.net/-/resource-impl/forward-origin-error
````

and the link is conveniently broken as well.

It looks like Pull Request https://github.com/akamai/AkamaiOPEN-edgegrid-golang/pull/74 was trying to fix this but has not been addressed.

**Comment by supernova2468** [comment]
I'm noticing three issues so far. 

1. The URI that is sent out includes {} around the contract id
2. There is no accept header added
3. The jsonhook unmarshal doesn't look to handle slices

**Comment by supernova2468** [comment]
I believe these changes solve the issue. @dshafik

**Comment by supernova2468** [comment]
Should be noted that this change is essentially the same as #74 but without changes to go.sum, and the ci seems to be passing.

**Comment by joel-g** [comment]
I am getting this same error with nearly the same code:

```
package main

import (
	"fmt"
	"log"
	"github.com/akamai/AkamaiOPEN-edgegrid-golang/cps-v2"
	"github.com/akamai/AkamaiOPEN-edgegrid-golang/edgegrid"
)

func main() {
	cfg, err := edgegrid.Init("~/.edgerc", "default")
	if err != nil {
		log.Fatal(err)
	}
	cps.Init(cfg)

	el, err := cps.ListEnrollments(cps.ListEnrollmentsQueryParams{ContractID: "X-XXXXXX"})
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(el)
}
```

**Comment by joel-g** [comment]
Oh my. I just realized that [PR #74](https://github.com/akamai/AkamaiOPEN-edgegrid-golang/pull/74) which solves this was actually opened by me in March...

**Comment by supernova2468** [comment]
pull request merged
