### ISSUE TITLE
GetRecordList does not support pagination

### ISSUE THREAD

**Issue by hundt** [akamai/AkamaiOPEN-edgegrid-golang#93]
GetRecordList uses the /zone/recordsets API endpoint but does not support pagination, so it may be impossible to get all the matching records.

https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/9e9c0b/configdns-v2/record_lookup.go#L119

I think maybe it should just wrap GetRecordsets, which does support pagination, and add extra optional parameters to be passed through? But I don't really understand the API for GetRecordList (it takes a "name" parameter which seems to only be used when constructing an error?) so I'm not sure.

**Comment by robertolopezlopez** [comment]
Hi @hundt ,

Sorry for this late answer. I hope, not too late.

Yes, I can see that this method does not support pagination - while [its API endpoint](https://techdocs.akamai.com/edge-dns/reference/get-zones-zone-recordsets) does. Unfortunately, we rarely touch / fix the dns package. And I can see that fixing this would require breaking changes for other clients already using this method. It may be done, but just with a good reason.

In the meanwhile, I have found out another method which you may be able to use: [GetRecordsets](https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/9e9c0bd9cfce56eca30ee840258c2ab8fd1c0b0b/configdns-v2/recordsets.go#L57). It is calling the same endpoint as GetRecordsets and supports the pageSize and page parameters.

I will close this issue ticket here, and if you still have problems using pagination with the proposed method just reopen it and we will consider refactoring GetRecordsets.

Regards,

Roberto
